name: GitHub Actions Demo
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [run_my_workflow]
jobs:
  Example-Actions-Job:
    name: Exploring GitHub Actions
    runs-on: ubuntu-latest
    env:
      GLOBAL_VERSION: "v1"
    steps:
      - run: echo 'Global Version\: ${{ env.GLOBAL_VERSION }}'
      - run: echo "My test env value is ${{ env.TEST_VALUE }}"
        env:
          GLOBAL_VERSION: "v212586"
      # Display the event that triggered the workflow
      - run: echo "Payload field is ${{ github.event.client_payload.mydata }}"

      # Use Action located in https://github.com/actions
      - name: Check out repository code
        uses: actions/checkout@v2  
      
      - name: conditional step when event name is pull request
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "This event is a pull request"
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - name: Setup dotnet on runner
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.x'
      
      - name: Display dotnet version
        run: dotnet --version
      
      - run: echo "The preinstalled tools are located here on the runner ${{ runner.tool_cache }}."
      
      - name: List files in tool cache
        run: |
          ls ${{ runner.tool_cache }}
      
      - run: echo "This job's status is ${{ job.status }}."
      
  Second-Actions-Job:
    name: My Second job running on another runner
    runs-on: ubuntu-latest
    needs: Example-Actions-Job
    steps:
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GH."
